### ISSUE TITLE
Hamburger icon on  Main screen to open

### ISSUE THREAD

**Issue by kprathap23** [lemonade-hq/SlideSideMenu#1]
UI Looks Pretty good.. is there any way to open slide menu on onclick event like click on hambuger icon on the Main Screen to open SlideMenu

**Comment by EyalBira** [comment]
Hi, thanks! Of course there is:

`SlideSideMenuTransitionLayout.toggle();`

I have added a toolbar with the hamburger icon to the example activity, please check it out.

**Comment by mbhanen** [comment]
hello sir , it s possible to animate the  SlideSideMenuTransitionLayout from right to left
